/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources./**/*.vue",
    ],
  theme: {
    colors: {
        'orange-dark': '#81030d',
        'orange-medium-dark': '#d22a12',
        'orange-medium-light': '#f3320d',
        'orange-light': '#fb5115',
        'yellow-dark': '#b27106',
        'yellow-medium-dark': '#eba503',
        'yellow-medium-light': '#fcc104',
        'yellow-light': '#fde701',
        'blue-dark': '#0750b9',
        'blue-medium-dark': '#0257d2',
        'blue-medium-light': '#046ce9',
        'blue-light': '#00b1fd',
        'green-dark': '#046e71',
        'green-medium-dark': '#00b87d',
        'green-medium-light': '#00c586',
        'green-light': '#00d29f',
        'pink-dark': '#860068',
        'pink-medium-dark': '#d4009f',
        'pink-medium-light': '#da01a3',
        'pink-light': '#f100bd',
        'purple-dark': '#a10194',
        'purple-medium': '#b000ab',
        'purple-light': '#b101b1',
        'black-dark': '#000001',
        'black-medium-dark': '#070a0b',
        'black-medium-light': '#141414',
        'black-light': '#22211f',
        'white': '#ffffff',
        },
  },
  plugins: [],
}

